config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#               home_index GET    /home/index(.:format)          home#index
#                home_show GET    /home/show(.:format)           home#show
#         new_user_session GET    /users/sign_in(.:format)       users/sessions#new
#             user_session POST   /users/sign_in(.:format)       users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      users/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        users/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          users/registrations#edit
#        user_registration PATCH  /users(.:format)               users/registrations#update
#                          PUT    /users(.:format)               users/registrations#update
#                          DELETE /users(.:format)               users/registrations#destroy
#                          POST   /users(.:format)               users/registrations#create
#                  sign_in GET    /sign_in(.:format)             users/sessions#new
#                 sign_out GET    /sign_out(.:format)            users/sessions#destroy
#                     root GET    /                              home#index
#          show_list_index GET    /show_list/index(.:format)     show_list#index
#            show_list_new GET    /show_list/new(.:format)       show_list#new
#         show_list_create POST   /show_list/create(.:format)    show_list#create
#

Rails.application.routes.draw do
  get 'home/index'

  get 'home/show'

  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  root 'show_list#index'
  get 'show_list/index'
  get 'show_list/download'
  get 'show_list/new'
  post 'show_list/create'

  resources :likes, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  want_list_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :want_list, :counter_cache => :want_lists_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, want_list_id: params[:id])
    @wantlist_target = WantList.find(params[:id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, want_list_id: params[:id])
    like.destroy
    @wantlist_target = WantList.find(params[:id])
  end
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if wantlist.has_liked?(current_user.id) %>
    <%# "delete" %>
    <%= button_to like_url(id: wantlist.id), method: :delete, remote: true do %>
      <i class="fa fa-heart fa-2x faa-pulse animated-hover fa-color-selected"></i>
      <%= wantlist.want_lists_count %>
    <% end %>
  <% else %>
    <%# "create" %>
    <%= button_to likes_url(id: wantlist.id), remote: true do %>
      <i class="fa fa-heart fa-2x faa-pulse animated-hover fa-color-normal"></i>
      <%= wantlist.want_lists_count %>
    <% end %>
  <% end %>
<% else %>
  <%= button_to likes_url(id: wantlist.id), remote: true, disabled: true do %>
    <i class="fa fa-heart fa-2x faa-pulse animated-hover fa-color-normal"></i>
    <%= wantlist.want_lists_count %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-button<%= @wantlist_target.id %>").html("<%= j(render partial: '/likes/like', locals: { wantlist: @wantlist_target}) %>")
<% p @wantlist %>
<% p "test" %>

app/views/likes/destroy.js.erb
$("#like-button<%= @wantlist_target.id %>").html("<%= j(render partial: '/likes/like', locals: { wantlist: @wantlist_target}) %>")