config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#               home_index GET    /home/index(.:format)          home#index
#                home_show GET    /home/show(.:format)           home#show
#         new_user_session GET    /users/sign_in(.:format)       users/sessions#new
#             user_session POST   /users/sign_in(.:format)       users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      users/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        users/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          users/registrations#edit
#        user_registration PATCH  /users(.:format)               users/registrations#update
#                          PUT    /users(.:format)               users/registrations#update
#                          DELETE /users(.:format)               users/registrations#destroy
#                          POST   /users(.:format)               users/registrations#create
#                  sign_in GET    /sign_in(.:format)             users/sessions#new
#                 sign_out GET    /sign_out(.:format)            users/sessions#destroy
#                     root GET    /                              home#index
#          show_list_index GET    /show_list/index(.:format)     show_list#index
#            show_list_new GET    /show_list/new(.:format)       show_list#new
#         show_list_create POST   /show_list/create(.:format)    show_list#create
#

Rails.application.routes.draw do
  get 'home/index'

  get 'home/show'

  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  root 'show_list#index'
  get 'show_list/index'
  get 'show_list/download'
  get 'show_list/new'
  post 'show_list/create'

  resources :likes, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/show_list_controller.rb
class ShowListController < ApplicationController
require 'csv'
  #before_action :authenticate_user!
  def new
    @wantlists = WantList.new
  end

  # GET /show_list/index
  def index
    @wantlists = WantList.all
    respond_to do |format|
      format.html
      format.csv do
        filename = 'csv_data.csv'
      end
    end
  end

  def create
    input_data = wantlist_params
    @wantlists = WantList.new(
      {
       user_id: current_user&.id || UserConfig::NOT_LOGIN_USER,
       product:input_data[:product],
       url:input_data[:url],
       want_lists_count: 1,
       comment:input_data[:comment]
      }
    )

    respond_to do |format|
      if @wantlists.save
        format.html { redirect_to @wantlists, notice: 'User was successfully created.' }
        format.json { render :index, status: :created, location: @wantlists }
        format.js { @status = "success"}
      else
        format.html { render :new }
        format.json { render json: @wantlists.errors, status: :unprocessable_entity }
        format.js { @status = "fail" }
      end
    end
    redirect_to :action => "index"
  end

  def download
    @wantlists = WantList.all
    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: 'wantlists.csv', type: :csv
      end
    end
  end

  private

  def wantlist_params
    params.require(:want_list)
  end
end

app/helpers/show_list_helper.rb
module ShowListHelper
  def tec
    "sholisthelperhome"
  end
end

app/views/show_list/_contents.html.erb
<% wantlists.each_with_index do |wantlist, ix| %>
  <tr>
    <th scope="row"><%= ix + 1 %></th>
    <td><%= wantlist.product %></td>
    <td><%= wantlist.url %></td>
    <td><%= wantlist.comment %></td>
    <%# いいねボタンのidを連番で採番 %>
    <td id="like-button<%= wantlist.id %>">
      <%= render :partial => "/likes/like", locals: {wantlist: wantlist} %>
    </td>
  </tr>
<% end %>

app/views/show_list/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_with(model: @wantlists,remote: true, url: show_list_create_path) do |f| %>
      <% if @wantlists.errors.any? %>
        <div id="error_explanation">

          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @wantlists.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">欲しいものを登録</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group field">
          <%= f.label "商品名[必須]" , class: "form-control-label"%>
          <%= f.text_field :product, id: :product, class: "form-control" %>
        </div>
        <div class="form-group field">
          <%= f.label :url , class: "form-control-label"%>
          <%= f.text_field :url, id: :url, class: "form-control" %>
        </div>
        <div class="form-group field">
          <%= f.label :ひとこと , class: "form-control-label"%>
          <%= f.text_field :comment, id: :comment, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer actions">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= f.submit "登録", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

app/views/show_list/index.html.erb
<div class="right-down-menu">
  <%= link_to 'リスト登録', show_list_new_path, remote: true, class: "btn btn-lg btn-danger" %>
  <br>
  <%= link_to 'ダウンロード', show_list_download_path(format: :csv), class: "btn btn-lg btn-info" %>
</div>
<div id="create-user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<table class="table">
  <thead class="table-warning">
    <tr>
      <th>#</th>
      <th>欲しいもの</th>
      <th>URL</th>
      <th>ひとこと</th>
      <th>欲しい！</th>
    </tr>
  </thead>
  <tbody id="like-buttons" class="">
    <%= render :partial => "/show_list/contents", locals: {wantlists: @wantlists} %>
  </tbody>
</table>

app/views/show_list/new.js.erb
$("#create-user-modal").html("<%= escape_javascript(render 'form') %>")
$("#create-user-modal").modal("show")